name: Almacenamiento en S3

on:
  push:
    branches:
      - main  # Cambia esto según tu rama principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Configurar AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-session-token: ${{ secrets.AWS_TOKEN_ACCESS_KEY }}
        aws-region: "us-east-1"  
    - name: Subir a S3
      run: aws s3 sync . s3://erikmiles
